. ./comm.sh

mysql -t -uroot -h127.0.0.1 -P3306 -pmysql << EOL

SELECT USERHOST, MODE 
FROM INFORMATION_SCHEMA.MYSQL_FIREWALL_USERS 
;
SELECT USERHOST, RULE 
FROM INFORMATION_SCHEMA.MYSQL_FIREWALL_WHITELIST 
;
EOL
