version: '3'
services:
  mysql-server-1:
    hostname: mysql-server-1
    container_name: mysql-server-1
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
        - /opt/mysql-commercial-8.0.13-el7-x86_64/:/usr/local/mysql/
  mysql-server-2:
    hostname: mysql-server-2
    container_name: mysql-server-2
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
  mysql-server-3:
    hostname: mysql-server-3
    container_name: mysql-server-3
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
  mysql-shell:
    env_file:
      - mysql-shell.env
    image: mysql-shell-8013
    command: ["/run.sh", "mysqlsh"]
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
  mysql-router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure
  dbwebapp:
    env_file:
      - dbwebapp.env
    image: neumayer/dbwebapp
    ports:
      - "8080:8080"
    depends_on:
      - mysql-router

